#MDTProject项目的相关配置
server:
  port: 7000
  tomcat: #tomcat编码方式
    uri-encoding: UTF-8

spring: #连接数据库
  datasource:
    jdbcUrl: jdbc:mysql://d6.knowimage.cn:10120/mdt_test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mdt_dev
    password: mdt@dev
  redis: #redis的相关配置
    database: 6
    host: 47.101.198.33
    port: 6379
    password:
    timeout: 5000
    #修改文件上传大小

  servlet:
    multipart:
      #设置单个文件上传大小
      max-file-size: 10MB
        #设置总上传的数据大小
      max-request-size: 50MB
  http:  # spring编码方式
    encoding:
      charset: UTF-8
      force: true
      enabled: true
# 加入mybatis开发配置, 加入mapper.xml文件的位置, 在xml文件中会指向mapper的路径namespace="cn.knowimage.mapper.PathwayInfoMapper"
# ,cn.knowimage.mapper.PathwayInfoMapper必须与类名保持一致
mybatis:
  type-aliases-package: cn.knowimage.pojo.instance
  mapper-locations: classpath:mapper/*mapper.xml




